# Copy for Concept A. Client copy is verbatim; UI labels are marked in comments.
EN = dict(
  lang="en", html_lang="en",
  brand="1234 Ortho-K Vision Care", brand_zh=None,
  nav=[("#how","How it works"),("#doctor","Dr. Woo"),("#visit","First visit"),("#faq","Questions"),("#locations","Locations")],
  menu="Menu", close="Close", night="Night", day="Day",
  book="Book a consultation", message="Message us", call="Call",
  eyebrow="Ortho-k for children, ages 7–18",
  hero_h='Clear vision all day.<br><span class="nb-mark">No glasses at school.</span>',
  hero_sub="Your child wears special lenses while they sleep. In the morning, they take them out and see clearly. Ortho-k may also help slow down nearsightedness as they grow.",
  trust_title="Who you'll see",
  trust=[("👀","Dr. Paul T. Woo, OD"),("🌙","30 years of ortho-k experience"),("💬","Speaks English, Mandarin, Cantonese, and Taiwanese"),("📍","Two clinics: Alhambra and Walnut")],
  prob_h="Is your child's prescription going up every year?",
  prob_b="Nearsightedness often gets worse during the school years. Stronger glasses fix the blur, but they don't slow the change.",
  how_h="How ortho-k works",
  step_word="Step",
  steps=[("👀","Full eye exam and a map of the eye"),("📏","Custom lenses made for your child"),("🌙","Wear at night. See clearly all day.")],
  doc_eyebrow="Meet the doctor",
  doc_name="Dr. Paul T. Woo, OD",
  doc_lines=["30 years of ortho-k experience.","Speaks English, Mandarin, Cantonese, and Taiwanese."],
  langs=["English","Mandarin","Cantonese","Taiwanese"],
  photo="Photo: Dr. Woo with a child patient",
  visit_h="What happens at the first visit",
  draft="Placeholder copy",
  visit=["We talk with you about your child's eyes and daily routine.","Your child has a full eye exam and a map of the front of the eye.","Dr. Woo explains the results and answers your questions."],
  faq_h="Parent questions",
  faqs=["Is ortho-k safe for kids?","What age can my child start?","Is it hard for kids to put in the lenses?","How much does it cost?"],
  faq_a="Placeholder answer. Dr. Woo's team will write this in plain words for parents.",
  loc_h="Book a visit at either clinic",
  contact_title="Book or message — whatever is easiest",
  contact=[("📞","Call","(800) 991-8881"),("📅","Book online",None),("WC","WeChat",None),("LINE","LINE",None),("WA","WhatsApp",None)],
  alhambra=dict(name="Alhambra", zh="阿罕布拉診所", addr="1234 S. Garfield Ave., #105<br>Alhambra, CA 91801", hours="Tue & Fri 12–6 pm, Sat 12–4 pm"),
  walnut=dict(name="Walnut", zh="核桃市診所", addr="Address coming soon", hours="Hours coming soon"),
  hours_label="Hours", addr_label="Address", phone_label="Phone",
  phones='<span class="nb-nowrap">(800) 991-8881</span> · <span class="nb-nowrap">(626) 282-5388</span>',
  book_here="Book here", directions="Directions", soon_btn="Opening soon",
  map="Map", map_soon="Map coming soon",
  band_h="Book a consultation",
  band_b="Book online, or message us on WeChat, LINE, or WhatsApp.",
  footer_langs="Language", footer_locs="Locations", footer_contact="Contact",
  legal=["Privacy policy","Notice of privacy practices","Accessibility","Terms"],
  copyright="© 2026 1234 Ortho-K Vision Care",
  form=dict(parent="Parent name", phone="Phone", age="Child's age", loc="Preferred location", age_ph="Age", err="Please add a phone number so we can reach you.", hint="We'll text or call to confirm.", submit="Send request"),
)

ZH = dict(
  lang="zh", html_lang="zh-Hant",
  brand="1234 Ortho-K Vision Care", brand_zh="1234兒童視力矯正中心",
  nav=[("#how","如何運作"),("#doctor","認識胡醫師"),("#visit","第一次看診"),("#faq","家長常見問題"),("#locations","診所地點")],
  menu="選單", close="關閉", night="夜間", day="日間",
  book="預約諮詢", message="傳訊息給我們", call="打電話",
  eyebrow="兒童角膜塑型・7–18歲",
  hero_h='白天看得清楚，<br><span class="nb-mark">上學不用戴眼鏡。</span>',
  hero_sub="孩子晚上睡覺時戴上特製鏡片，早上取下就能看清楚。角膜塑型也可能幫助減緩近視加深。",
  trust_title="為孩子看診的是",
  trust=[("👀","胡超醫師，眼科視學博士"),("🌙","近30年角膜塑型經驗"),("💬","可說英語、普通話、粵語及台語"),("📍","兩間診所：阿罕布拉、核桃市")],
  prob_h="孩子的近視度數每年都在增加嗎？",
  prob_b="近視常在學齡期間加深。配更深的眼鏡能看清楚，但無法減緩度數增加。",
  how_h="角膜塑型怎麼進行",
  step_word="步驟",
  steps=[("👀","完整眼睛檢查與角膜地圖"),("📏","為孩子量身訂製鏡片"),("🌙","晚上配戴，白天清晰。")],
  doc_eyebrow="認識醫師",
  doc_name="胡超醫師，眼科視學博士",
  doc_lines=["近30年角膜塑型經驗。","可說英語、普通話、粵語及台語。"],
  langs=["英語","普通話","粵語","台語"],
  photo="照片：胡醫師與小病人",
  visit_h="第一次來診所會做什麼",
  draft="暫定文字",
  visit=["我們先和您聊聊孩子的眼睛和日常作息。","孩子會做完整的眼睛檢查，並拍攝角膜地圖。","胡醫師向您說明結果，並回答您的問題。"],
  faq_h="家長常見問題",
  faqs=["角膜塑型對孩子安全嗎？","孩子幾歲可以開始？","孩子自己戴鏡片會很難嗎？","費用大約多少？"],
  faq_a="暫定答案。胡醫師團隊會用家長容易理解的話來撰寫。",
  loc_h="兩間診所，歡迎預約",
  contact_title="預約或傳訊息，選您方便的方式",
  contact=[("📞","打電話","(800) 991-8881"),("📅","線上預約",None),("WC","微信 WeChat",None),("LINE","LINE",None),("WA","WhatsApp",None)],
  alhambra=dict(name="阿罕布拉診所", zh="Alhambra", addr="1234 S. Garfield Ave., #105<br>Alhambra, CA 91801", hours="週二及週五 中午12點至下午6點<br>週六 中午12點至下午4點"),
  walnut=dict(name="核桃市診所", zh="Walnut", addr="地址即將公佈", hours="門診時間即將公佈"),
  hours_label="門診時間", addr_label="地址", phone_label="電話",
  phones='<span class="nb-nowrap">(800) 991-8881</span> · <span class="nb-nowrap">(626) 282-5388</span>',
  book_here="在此預約", directions="路線導航", soon_btn="即將開放",
  map="地圖", map_soon="地圖即將公佈",
  band_h="預約諮詢",
  band_b="可以線上預約，也可以用微信、LINE 或 WhatsApp 傳訊息給我們。",
  footer_langs="語言", footer_locs="診所地點", footer_contact="聯絡我們",
  legal=["隱私權政策","病患隱私權通知","無障礙聲明","使用條款"],
  copyright="© 2026 1234 Ortho-K Vision Care",
  form=dict(parent="家長姓名", phone="電話", age="孩子年齡", loc="希望就診的診所", age_ph="年齡", err="請填寫電話號碼，方便我們聯絡您。", hint="我們會以簡訊或電話確認。", submit="送出預約"),
)
